### ISSUE TITLE
Moving SSL certificate with Nginx

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#866]
Hey Jamie!

Moving SSL certificate to the new location seems to work just fine with Apache. To be clear I mean this page:

<img width="1425" alt="image" src="https://github.com/user-attachments/assets/51004af6-f609-48f6-826e-1929e1c21aee">

However, when used with Nginx things are getting really broken:

<img width="1424" alt="image" src="https://github.com/user-attachments/assets/788bf6b2-a377-4973-905b-fbbb8d92a1b3">

It gets broken to the level that Webmin stops working, e.g.:

<img width="891" alt="image" src="https://github.com/user-attachments/assets/25b238ec-736c-41ef-a769-7801ae8d5d2b">

`miniserv.conf` in this case gets new records, like:

```
-certfile=/etc/webmin/host.ubuntu24-gpl.virtualmin.dev.cert
+certfile=/etc/webmin/ubuntu24-gpl.virtualmin.dev.cert
-keyfile=/etc/webmin/host.ubuntu24-gpl.virtualmin.dev.key
+keyfile=/etc/webmin/ubuntu24-gpl.virtualmin.dev.key
```

.. but those new files simply don't exist!

```
root@ubuntu24-gpl:/etc# ls -lsa /etc/webmin/ubuntu24-gpl.virtualmin.dev.key
ls: cannot access '/etc/webmin/ubuntu24-gpl.virtualmin.dev.key': No such file or directory
root@ubuntu24-gpl:/etc# ls -lsa /etc/webmin/ubuntu24-gpl.virtualmin.dev.cert
ls: cannot access '/etc/webmin/ubuntu24-gpl.virtualmin.dev.cert': No such file or directory
```

**Comment by jcameron** [comment]
Yikes! That's clearly a bug ... I will look into it

**Comment by iliajie** [comment]
Thanks!

**Comment by jcameron** [comment]
What about the SSL cert files in the domain's home directory - did those get renamed?

**Comment by iliajie** [comment]
If I remember correctly it did rename those!

Even though fixing the source of the bug is priority, yet I think we should probably eval that code, so it breaks for particular step in particular rather than causing the general issue.

**Comment by jcameron** [comment]
Ok, the patch I just attached to this ticket should fix it..

**Comment by iliajie** [comment]
I will test it and let you know if it works!

**Comment by iliajie** [comment]
I have tested it but sadly it doesn't fix the original issue:

<img width="1424" alt="image" src="https://github.com/user-attachments/assets/8c9544dd-4ffb-431e-804d-f7646c1d1407">

**Comment by jcameron** [comment]
If you check the domain's config file under /etc/webmin/virtual-server/domains, are the `ssl_cert` and `ssl_key` lines correct?

**Comment by iliajie** [comment]
> If you check the domain's config file under /etc/webmin/virtual-server/domains, are the `ssl_cert` and `ssl_key` lines correct?

No, domain config file not even touched.

**Comment by jcameron** [comment]
I'm so sorry .. try the further patch I just attached to this ticket.

**Comment by iliajie** [comment]
Thanks! That seems to be finished up properly now!

However, there is still a problem because the paths for shared SSL certificates weren't updated. Please look at this screenshot:

<img width="1309" alt="image" src="https://github.com/user-attachments/assets/956be896-5979-4a86-aee1-042780dff8c0">

To be clear, I was moving a domain's SSL certificates to `/home/domain`. While all the domain's records were updated correctly, the shared SSL certificates weren't:

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/96a37f77-9d4e-427b-b4d4-1130d483e383">
<img width="671" alt="image" src="https://github.com/user-attachments/assets/f7d4584f-b099-4add-9987-53223350b6c0">
<img width="812" alt="image" src="https://github.com/user-attachments/assets/6fbf64b9-4c89-4aa6-a8d8-3baa72c19796">
