### ISSUE TITLE
Deleting domain Alias - says it is going to delete its home directoy

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#937]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5             |
|  Usermin version     |  2.102                            |
|  Virtualmin version  |  7.20.2 Pro                       |
|  Theme version       |  21.20.7                          |
|  Apache version      |  2.4.52                           |
|  Package updates     |  8 package updates are available  |

### The issue

An domain alias should not have a home directory

![image](https://github.com/user-attachments/assets/d220d98e-ae7f-4042-8fac-d782a80d611a)

### solution

can you amend the notifications or tell me I am wrong? 😄

**Comment by iliajie** [comment]
Hello,

That’s odd! How does this alias domain look like in navigation menu dropdown?

**Comment by shoulders** [comment]
This is using  my main admin login
![image](https://github.com/user-attachments/assets/8aa84d30-02fb-4579-8bc2-ba7b2ec6fe71)

The one that start with hg. The primary is `.co.uk` and the aliase are `.uk` and `.com`

This account is from a cpanel import if it makes any dofference

**Comment by jcameron** [comment]
That message isn't really wrong - alias domains do still have a home directory.

**Comment by shoulders** [comment]
> alias domains do still have their own home directory.

They should not have one from an end- users point of view.

Is this a hidden folder used as a work around? Maybe the message on-screen needs changing as from what I read, it is going to delete my files.

does there even need to be a message saying it is going to delete the home folder if there are no user files or settings?

i.e. this home folder does not contain any userfiles and is just a requirement to allow aliases to work????

Clarification is definitely needed on this one.

thanks

**Comment by iliajie** [comment]
> > alias domains do still have their own home directory.
> 
> They should not have one from an end- users point of view.


@shoulders This only applies to aliases with their own email.

@jcameron In that case, we should show “Home directory” on the “Virtual Server Summary” page, but currently, we didn't. I have fixed that on the [associated commit](https://github.com/virtualmin/virtualmin-gpl/commit/b5ff93b99b6e09bc63be217c7a5de8c61794b691). Now I’m also wondering if we should allow editing alias home directory using the similar change here, as well:

https://github.com/virtualmin/virtualmin-gpl/blob/master/edit_domain.cgi#L90-L94

**Comment by jcameron** [comment]
It's almost always empty, so there's usually nothing to delete to be honest. I suppose we could hide this message for alias domains to avoid scaring users :-)

**Comment by shoulders** [comment]
Just incase this was not fixed, when you delete the alias you get the following, including deleting home page

```
Deleting mail aliases ..
.. done

Removing from target virtual website ..
.. done

Deleting home directory ..
.. done

Deleting server details for tonkatoys.uk ..
.. done

Updating Webmin user ..
.. done

Re-loading Webmin ..
.. done

Re-starting Usermin ..
.. done

Restarting mail server ..
.. done

Applying webserver configuration ..
.. done
```

**Comment by iliajie** [comment]
> It's almost always empty, so there's usually nothing to delete to be honest. I suppose we could hide this message for alias domains to avoid scaring users :-)

I don’t think this is the right approach! If the directory exists, we have to tell user about!?

**Comment by iliajie** [comment]
> Deleting home directory ..
> .. done

This is expected since the home directory exists. I already explained earlier that aliases with their own user have a home directory, and everything related to that had been already working correctly. I believe [this patch](https://github.com/virtualmin/virtualmin-gpl/commit/d8ca28cf19965fbbba7734aa72a723e36a30bc58) should be reverted rather than continuing down the wrong path...

**Comment by jcameron** [comment]
Yeah I think it's fine to keep that message

**Comment by shoulders** [comment]
**Consider the delete message**

> Home directory - the home directory for this virtual server, containing all website and otherwise, will be deleted.

**From the Docs**
> https://www.virtualmin.com/docs/getting-started/understanding-virtual-server-and-account-types/#understanding-virtual-server-aliases
> An alias allows a domain to act exactly like another, sharing the same website and email addresses. This is useful for having multiple domains like example.com and example.net display the same website content.

- The official docs even say they share the same website content and then in the delete message it clearly says it is going to delete all website content.
- As an `end-user` an alias does not have a home directory because it uses the website content of the parent

**my thoughts**
- Amend the message to actually match the docs and what people expect
or
- remove the message

**Comment by shoulders** [comment]
Much better message for alias. Less frightening and more consistent.

**Comment by iliajie** [comment]
> Much better message for alias. Less frightening and more consistent.

Thanks for pointing this out in the first place!
