### ISSUE TITLE
[ALERT] Big bug since the last Virtualmin / PHP-FPM update

### ISSUE THREAD

**Issue by SIP-Online** [virtualmin/virtualmin-gpl#981]
Hello,
I'm alerting you to a bug that caused a hell of a mess on version **7.30.2**.
All my spaces (Domains / Subdomains) are changed to PHP 8.2, after searching in (**Webmin Actions Log**), this is linked to the virtual-server/run-postinstalls.pl step:
```
> lastsave_script=/usr/share/webmin/run-postinstalls.pl
138c138
< php_fpm_version=8.0
---
> php_fpm_version=8.2
```

On another:
```
116c116
< php_fpm_version=7.4
---
> php_fpm_version=8.2
```
.....................................................
..................................
..............

This on all my web spaces in PHP 7.4, 8.0, 8.1...

On the tree side, everything is however still in the right places: **/etc/php/\*/fpm/pool.d/\***

This is clearly a bug that deserves to stop this update, because it will quickly degenerate Forums side.

I don't know how you're going to be able to catch up on this?
In the meantime, I've backed up the "**/etc/php**" folder

**Comment by SIP-Online** [comment]
I have corrected it manually for the moment, using the following folders: **/etc/php/\*/fpm/pool.d/***
Here are the corrected files (**php_fpm_version**): **/etc/webmin/virtual-server/domains/\***
And also this one: **/etc/webmin/phpini/\***

**Restarted webmin, and also emptied the Template cache.**

Fortunately there were few web spaces on this server, but I am eager to know when it will be corrected, so that I can continue updating my other servers.

I think a batch script can auto-correct this bug.

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

> All my spaces (Domains / Subdomains) are changed to PHP 8.2, after searching in (**Webmin Actions Log**), this is linked to the virtual-server/run-postinstalls.pl step:

What is set in "System Settings ⇾ Server Templates" for top level and sub domain for "PHP options" sub-page? Can you provide screenshots for it?


> This is clearly a bug that deserves to stop this update, because it will quickly degenerate Forums side.

Yet, I could not reproduce this bug. Could you provide more details? Which version of Virtualmin did you have installed before upgrading to Virtualmin 7.30.2? What changes, if any, were made to the PHP configuration after the package upgrade?

> I have corrected it manually for the moment, using the following folders: **/etc/php/*/fpm/pool.d/***
> Here are the corrected files (**php_fpm_version**): **/etc/webmin/virtual-server/domains/***
> And also this one: **/etc/webmin/phpini/***

What exactly have you corrected?

> Restarted webmin, and also emptied the Template cache.

What does it mean to empty the template cache?

> I think a batch script can auto-correct this bug.

Do you have an idea of what that script would look like or what it did?

**Comment by SIP-Online** [comment]
1) I'm attaching the file:
![PHP_options](https://github.com/user-attachments/assets/16a4e633-5991-4c51-850c-5eb486c6b7de)

2) Unfortunately, I won't be able to find this information, because I emptied a good part of the /var/webmin folder for the restoration, except of course the **/var/webmin/modules folder**
Luckily, I found this in the file (**/var/webmin/modules/virtual-server/installtimes**):
**7.20.2=1732565128
7.30.2=1733764498**

So I would say that it's version **7.20.2**

2) For **/etc/webmin/virtual-server/domains/\***, it's the key (**php_fpm_version**), since the script (**/usr/share/webmin/run-postinstalls.pl**) broke them all for me at PHP 8.2
**/etc/webmin/phpini/\*** contains the paths to the file, I had to put them back good versions so that Virtualmin can show me the PHP-FPM settings again.

3) In the Theme Configuration (**Graphic**), you have a button that allows this: **Clear cache**

**Comment by jcameron** [comment]
I'd also be interested to see what PHP versions your Virtualmin thinks are installed, by running : 

```
virtualmin list-php-versions --multiline
```

**Comment by SIP-Online** [comment]
Here it is, from a SURY repository:
```
virtualmin list-php-versions --multiline
5.6
    Command: /bin/php-cgi5.6
    CLI: /bin/php5.6
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 5.6.40
7.2
    Command: /bin/php-cgi7.2
    CLI: /bin/php7.2
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 7.2.34
7.4
    Command: /bin/php-cgi7.4
    CLI: /bin/php7.4
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 7.4.33
8.0
    Command: /bin/php-cgi8.0
    CLI: /bin/php8.0
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 8.0.30
8.1
    Command: /bin/php-cgi8.1
    CLI: /bin/php8.1
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 8.1.31
8.2
    Command: /bin/php-cgi8.2
    CLI: /bin/php8.2
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 8.2.26
8.3
    Command: /bin/php-cgi8.3
    CLI: /bin/php8.3
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 8.3.14
```

If it can help, it is a server that was migrated not even 1 month ago, and therefore restored with backups from another server under the same version of Virtualmin.
Before the migration, I had checked on each web space that the PHP-FPM parameters were correct, the restoration was perfectly done.
Maybe the restoration step ignored important parameters in the confs of the web spaces between the old and the new server?
Concerning my Virtuamin settings (Template & Configuration) they are put back in the same way, I have been doing this for years through a homemade script.

**Comment by iliajie** [comment]
> Maybe the restoration step ignored important parameters in the confs of the web spaces between the old and the new server?

Ahh, bingo!! If the `php_fpm_version` directive is missing from the domain config, Virtualmin incorrectly assumes that the higher/highest PHP version isn’t set properly (even though it's actually still correctly configured to PHP 8.3 in this case) and displays:

<img width="933" alt="image" src="https://github.com/user-attachments/assets/1339b7a3-bfd2-4282-8363-b0515c427909">

---

The “PHP-FPM Configuration” link in the menu also doesn’t correctly point to the right PHP version.

Jamie, I reproduced this issue with two PHP versions installed on the system: 8.1 and 8.3. The domain in question was set to use PHP 8.3, and the template is configured to use the highest available PHP version in FPM mode. Then, I manually edited the domain config file and removed the `php_fpm_version` directive from it. Then, visiting the "PHP Options" page triggered a yellow warning alert. Clicking the save button to “fix it” switched the PHP version to the lower one (the one incorrectly selected on the dropdown).

To be clear, the PHP pool and Nginx webserver configurations were correct.

**Comment by SIP-Online** [comment]
I confirm that the **php_fpm_version** parameter was there, because Webmin Actions Log displays it (see my first Post).

The big question is why the script **/usr/share/webmin/run-postinstalls.pl** changed all my **php_fpm_version** to PHP 8.2 (all those that were below PHP 8.2), this during this update phase from version 7.20.2 to 7.30.2.
Even more bizarre, it did not touch the versions that were in 8.2 and 8.3, so we can say 8.2 and above.

**Comment by jcameron** [comment]
The root cause has to be in this code here, which checks if any domains have the PHP FPM version set to something that doesn't exist on the system : https://github.com/virtualmin/virtualmin-gpl/blob/master/virtual-server-lib-funcs.pl#L16064

This is supposed to protect against the case where PHP has been upgraded "underneath" Virtualmin, but it seems like here that has gone wrong. 

@iliajie the issue you found Virtualmin not handling a missing `php_fpm_version` line isn't related to this, and is expected

**Comment by iliajie** [comment]
> The root cause has to be in this code here, which checks if any domains have the PHP FPM version set to something that doesn't exist on the system : https://github.com/virtualmin/virtualmin-gpl/blob/master/virtual-server-lib-funcs.pl#L16064
> 
> This is supposed to protect against the case where PHP has been upgraded "underneath" Virtualmin, but it seems like here that has gone wrong.
> 
> @iliajie the issue you found Virtualmin not handling a missing `php_fpm_version` line isn't related to this, and is expected

Alright, thanks! I have added a PR, and some other comments—let's discuss it.

**Comment by jcameron** [comment]
@SIP-Online also what output do you get if you run `virtualmin list-php-versions --domain example.com --multiline` where `example.com` is one of the domains that had the config messed up?

@iliajie I think at the very least we should not run this "fix" in the post-install script, but rather show users a warning on the dashboard with a button to fix it.

**Comment by SIP-Online** [comment]
> @SIP-Online also what output do you get if you run `virtualmin list-php-versions --domain example.com --multiline` where `example.com` is one of the domains that had the config messed up?

I took a domain from the server:
```
virtualmin list-php-versions --domain loki-kids.com --multiline
5.6
    Command: /bin/php-cgi5.6
    CLI: /bin/php5.6
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 5.6.40
7.2
    Command: /bin/php-cgi7.2
    CLI: /bin/php7.2
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 7.2.34
7.4
    Command: /bin/php-cgi7.4
    CLI: /bin/php7.4
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 7.4.33
8.0
    Command: /bin/php-cgi8.0
    CLI: /bin/php8.0
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 8.0.30
8.1
    Command: /bin/php-cgi8.1
    CLI: /bin/php8.1
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 8.1.31
8.2
    Command: /bin/php-cgi8.2
    CLI: /bin/php8.2
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 8.2.26
8.3
    Command: /bin/php-cgi8.3
    CLI: /bin/php8.3
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 8.3.14
```

**Comment by SIP-Online** [comment]
> @SIP-Online also what output do you get if you run `virtualmin list-php-versions --domain example.com --multiline` where `example.com` is one of the domains that had the config messed up?

I took a domain from the server, this one is in PHP 7.4:
```
virtualmin list-php-versions --domain loki-kids.com --multiline
5.6
    Command: /bin/php-cgi5.6
    CLI: /bin/php5.6
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 5.6.40
7.2
    Command: /bin/php-cgi7.2
    CLI: /bin/php7.2
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 7.2.34
7.4
    Command: /bin/php-cgi7.4
    CLI: /bin/php7.4
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 7.4.33
8.0
    Command: /bin/php-cgi8.0
    CLI: /bin/php8.0
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 8.0.30
8.1
    Command: /bin/php-cgi8.1
    CLI: /bin/php8.1
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 8.1.31
8.2
    Command: /bin/php-cgi8.2
    CLI: /bin/php8.2
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 8.2.26
8.3
    Command: /bin/php-cgi8.3
    CLI: /bin/php8.3
    PHP modes: fpm fcgid cgi
    FPM support: Yes
    Full version: 8.3.14
```

**Comment by jcameron** [comment]
> ...also, do we really need [this](https://github.com/virtualmin/virtualmin-gpl/commit/ce3d7f31794f510b4db8a300eda0b965a7af459f) code in the post-install?

Yes, but also it's unrelated to this issue

**Comment by iliajie** [comment]
> > ...also, do we really need [this](https://github.com/virtualmin/virtualmin-gpl/commit/ce3d7f31794f510b4db8a300eda0b965a7af459f) code in the post-install?
> 
> Yes, but also it's unrelated to this issue

Didn't you mention that there was some code related to this issue in Virtualmin post-install? And, what about [this other](https://github.com/virtualmin/virtualmin-gpl/issues/981#issuecomment-2535941630) comment?

**Comment by jcameron** [comment]
> However, after taking another look, [this specific code](https://github.com/virtualmin/virtualmin-gpl/commit/7108b8f6d604acd5a3b7605f3f050bf16b0cb42b#diff-31ff62c54bfd41f4bcafe214f1cca2dca5ce14247c2d97664222262fd78e2ed1R312-R318) raises a red flag for me. It seems wrong because we shouldn’t care about the PHP execution mode for aliases, as they don’t have separate virtual host records.

That's not super important, but it's handy when an alias domain is looked up to know what PHP mode the real domain will be using.

**Comment by iliajie** [comment]
> That's not super important, but it's handy when an alias domain is looked up to know what PHP mode the real domain will be using.

That makes sense! Agreed. However, we’re not doing this correctly in normal operations—if the PHP mode is changed on the parent, it doesn’t update the alias accordingly!

**Comment by SIP-Online** [comment]
Hello to both of you,
I wanted to bring you new information, I made updates on two other servers, and everything went well.
The track of a backup restoration, then a few weeks later the update with this Bug, must be I think the track to take.
I have very little time at the moment, otherwise I could have redone exactly the same procedure with two VMs (old server that saves / New server that restores with installation of a Virtualmin 7.20.2), to see if it does the same thing by launching an update to a recent version afterwards.

**Comment by jcameron** [comment]
@SIP-Online I think the trigger may be a glitch where Virtualmin fails to detect all the FPM versions available, and thus tries to "fix" an issue that doesn't need fixing. I will work on a more stable solution to this issue.

**Comment by jcameron** [comment]
> That makes sense! Agreed. However, we’re not doing this correctly in normal operations—if the PHP mode is changed on the parent, it doesn’t update the alias accordingly!

@iliajie that should be fixed here : https://github.com/virtualmin/virtualmin-gpl/commit/cbf010eb72280398d757b154866f38012255410e

**Comment by iliajie** [comment]
> > That makes sense! Agreed. However, we’re not doing this correctly in normal operations—if the PHP mode is changed on the parent, it doesn’t update the alias accordingly!
> 
> @iliajie that should be fixed here : [cbf010e](https://github.com/virtualmin/virtualmin-gpl/commit/cbf010eb72280398d757b154866f38012255410e)

Thanks, Jamie! Not entirely, though! 

1. With the Apache, it’s still not creating any record at the time of alias creation.
2. With Nginx, the new code never reaches the patch and exits after line 262 (i.e., `$d->{'php_mode'} = $mode if (!$err);`).

**Comment by iliajie** [comment]
Jamie, I have found something else!

Using a Debian 12 (Nginx system) snapshot with a clean Virtualmin 7.20.2 and a single PHP version installed, I added PHP version 8.0. Note that at that point in time, the domain had PHP-FPM 8.2 configured on the "PHP Options" page, and it was displayed correctly without any errors. After the installation, nothing changed. _However_, running the Virtualmin config check revealed the following change, which I'm not sure should happen at all, e.g.:



<img width="1122" alt="image" src="https://github.com/user-attachments/assets/74509eeb-e4a7-4ec1-af26-c3c60dd1135a" />

---

I refer to this change:

```diff
-php_inis=/etc/php/8.2/fpm/pool.d/172355607241220.conf=PHP configuration for debian12-pro.virtualmin.dev
+php_inis=/etc/php/8.0/fpm/pool.d/172355607241220.conf=PHP configuration for debian12-pro.virtualmin.dev
```


Is this expected? I don't think it is:

```bash
root@debian12-pro:/etc# ls -lsa /etc/php/8.0/fpm/pool.d/172355607241220.conf
ls: cannot access '/etc/php/8.0/fpm/pool.d/172355607241220.conf': No such file or directory
```

**Comment by jcameron** [comment]
So did you change the domain's PHP version to 8.0 at some point? It looks like maybe the .acl file was just out of date...

**Comment by iliajie** [comment]
No, I didn’t change it! It wasn’t changed either. PHP info has always been showing to 8.2. And, it still is.

**Comment by jcameron** [comment]
Does that `/etc/php/8.0/fpm/pool.d/172355607241220.conf` file even exist?

**Comment by iliajie** [comment]
> Does that `/etc/php/8.0/fpm/pool.d/172355607241220.conf` file even exist?

No, of course it doesn't!

**Comment by jcameron** [comment]
@iliajie could you open a separate ticket for this? It seems unrelated to the OP's issue

**Comment by iliajie** [comment]
> Could you open a separate ticket for this?

Done here https://github.com/virtualmin/virtualmin-gpl/issues/988#issue-2751248608.

> It seems unrelated to the OP's issue

I think this ticket is resolved and can be closed?
